
FROM python:3.10-alpine

ADD . /mystalker
WORKDIR /mystalker

RUN pip install -e .

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONHASHSEED 0
ENV PYTHONUNBUFFERED 1

ENTRYPOINT [ "python3.10", "-u", "/mystalker/mystalker.py" ]
